import fs from 'node:fs';import assert from 'node:assert/strict';import * as T from 'three';import {loader,charts,meshes,key,bytes,dir} from './loader.mjs';
const m=[loader(false),loader(true)],a=m.map(v=>v.load('src/world/character/link.ts').createLink()),g=a.map(v=>v.rig.head.getObjectByName('hair').geometry),c=g.map(charts),report={charts:c.map(v=>v.length),vertices:g.map(v=>v.attributes.position.count),triangles:g.map(v=>v.index.count/3),protectedMeshes:0,protectedArrays:0,protectedCharts:[],protectedRootVertices:0,protectedTempleVertices:0,topology:[],failure:null};
try{assert.deepEqual(report.charts,[22,26]);assert(bytes(g[0].index.array).equals(bytes(g[1].index.array.slice(0,g[0].index.count))),'entire original hair index prefix');const before=new Map(meshes(a[0]).map(v=>[key(v),v]));for(const mesh of meshes(a[1])){if(mesh.name==='hair')continue;const old=before.get(key(mesh));assert(old);for(const n of Object.keys(mesh.geometry.attributes)){assert(bytes(mesh.geometry.attributes[n].array).equals(bytes(old.geometry.attributes[n].array)),key(mesh)+n);report.protectedArrays++;}if(mesh.geometry.index){assert(bytes(mesh.geometry.index.array).equals(bytes(old.geometry.index.array)));report.protectedArrays++;}assert.deepEqual(mesh.position.toArray(),old.position.toArray());assert.deepEqual(mesh.quaternion.toArray(),old.quaternion.toArray());assert.deepEqual(mesh.scale.toArray(),old.scale.toArray());assert.equal(mesh.castShadow,old.castShadow);assert.equal(mesh.receiveShadow,old.receiveShadow);report.protectedMeshes++;}
for(let ci=0;ci<22;ci++){if(ci>=6&&ci<=13)continue;assert.deepEqual(c[0][ci],c[1][ci]);for(const n of Object.keys(g[0].attributes)){const old=g[0].attributes[n],next=g[1].attributes[n];for(const i of c[0][ci].vertices)for(let j=0;j<old.itemSize;j++)assert.equal(next.array[i*old.itemSize+j],old.array[i*old.itemSize+j],`protected chart ${ci} ${n}`);}report.protectedCharts.push(ci);}
for(let ci=6;ci<14;ci++){const i=c[0][ci].vertices[336];for(let j=0;j<3;j++)assert.equal(g[1].attributes.position.array[i*3+j],g[0].attributes.position.array[i*3+j],`root anchor ${ci}`);report.protectedRootVertices++;if(ci>=12)for(const vi of [...Array.from({length:48},(_,i)=>288+i),337]){const i=c[0][ci].vertices[vi];for(const n of ['position','normal'])for(let j=0;j<3;j++)assert.equal(g[1].attributes[n].array[i*3+j],g[0].attributes[n].array[i*3+j],`temple ${ci}/${vi} ${n}`);report.protectedTempleVertices++;}}

for(const ci of [...Array.from({length:8},(_,i)=>i+6),22,23,24,25]){const p=g[1].attributes.position,n=g[1].attributes.normal,ix=g[1].index,chart=c[1][ci],edges=new Map();let areaMin=Infinity,volume=0,cornerMin=Infinity,negativeCorners=0;const av=new T.Vector3(),bv=new T.Vector3(),cv=new T.Vector3(),fn=new T.Vector3(),nn=new T.Vector3();for(const f of chart.faces){const ids=[0,1,2].map(j=>ix.getX(f*3+j));av.fromBufferAttribute(p,ids[0]);bv.fromBufferAttribute(p,ids[1]);cv.fromBufferAttribute(p,ids[2]);const tri=new T.Triangle(av,bv,cv),area=tri.getArea();areaMin=Math.min(areaMin,area);assert(area>0,`zero face ${ci}/${f}`);tri.getNormal(fn);volume+=av.dot(bv.clone().cross(cv))/6;for(const i of ids){nn.fromBufferAttribute(n,i);assert(nn.toArray().every(Number.isFinite));const dot=nn.dot(fn);cornerMin=Math.min(cornerMin,dot);if(dot<0)negativeCorners++;}for(let j=0;j<3;j++){const x=ids[j],y=ids[(j+1)%3],k=Math.min(x,y)+','+Math.max(x,y);const edge=edges.get(k)||{count:0,balance:0};edge.count++;edge.balance+=x<y?1:-1;edges.set(k,edge);}}assert([...edges.values()].every(v=>v.count===2&&v.balance===0));assert(volume>0);report.topology.push({chart:ci,vertices:chart.vertices.length,faces:chart.faces.length,areaMin,volume,cornerMin,negativeCorners});}
}catch(e){report.failure=e.message;}
fs.writeFileSync(dir+'/geometry-result.json',JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify(report,null,2));assert.equal(report.failure,null);
