import fs from 'node:fs';import path from 'node:path';import{execFileSync}from'node:child_process';import{fileURLToPath}from'node:url';import ts from 'typescript';import * as T from 'three';import * as U from 'three/addons/utils/BufferGeometryUtils.js';
export const root=process.cwd(),evidenceDir=path.dirname(fileURLToPath(import.meta.url)),dir=path.resolve('gauntlet/tmp/astra-layered-fringe-evidence-replay');fs.mkdirSync(dir,{recursive:true});const baselineSources=new Map();const pin='9a317b873eae4a036e0ad179027201fdfdb217c1';function baselineSource(local){if(!baselineSources.has(local))baselineSources.set(local,execFileSync('git',['show',pin+':'+local],{cwd:root,encoding:'utf8'}));return baselineSources.get(local);}
const ctx=new Proxy({}, {get:(_,k)=>String(k).endsWith('Gradient')?()=>({addColorStop(){}}):k==='createImageData'?(w,h)=>({data:new Uint8ClampedArray(w*h*4)}):()=>{}});globalThis.document={createElement:()=>({width:0,height:0,getContext:()=>ctx})};
export function loader(candidate){const cache=new Map();function load(rel){const file=path.resolve(root,rel);if(cache.has(file))return cache.get(file).exports;const local=path.relative(root,file),overlay=path.join(typeof candidate === 'string' ? candidate : path.join(evidenceDir,'candidate'),local);let source=candidate&&fs.existsSync(overlay)?fs.readFileSync(overlay,'utf8'):baselineSource(local);if(file.endsWith('/link.ts'))source=source.replace('  batchStaticLinkParts(rig);','');const m={exports:{}};cache.set(file,m);new Function('require','module','exports',ts.transpileModule(source,{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText)(id=>id==='three'?T:id.includes('BufferGeometryUtils')?U:load(path.resolve(path.dirname(file),id+'.ts')),m,m.exports);return m.exports;}return{load};}
export function charts(g){const p=g.attributes.position,ix=g.index,parents=Array.from({length:p.count},(_,i)=>i);const root=i=>{while(parents[i]!==i){parents[i]=parents[parents[i]];i=parents[i];}return i;};for(let i=0;i<ix.count;i+=3){const a=root(ix.getX(i));parents[root(ix.getX(i+1))]=a;parents[root(ix.getX(i+2))]=a;}const out=new Map();for(let i=0;i<p.count;i++){const a=root(i);if(!out.has(a))out.set(a,{vertices:[],faces:[]});out.get(a).vertices.push(i);}for(let i=0;i<ix.count;i+=3)out.get(root(ix.getX(i))).faces.push(i/3);return [...out.values()];}
export const key=o=>{let parts=[];for(let n=o;n.parent;n=n.parent)parts.push(n.name+':'+n.parent.children.filter(x=>x.name===n.name).indexOf(n));return parts.reverse().join('/');};
export function meshes(a){const out=[];a.group.traverse(o=>{if(o.isMesh)out.push(o)});return out;}
export const bytes=a=>Buffer.from(a.buffer,a.byteOffset,a.byteLength);
export function chartGeometry(g,chart){const h=g.clone();h.setIndex(chart.faces.flatMap(f=>[0,1,2].map(j=>g.index.getX(f*3+j))));return h;}
